# for creating the namespace if it's missing
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  # change if needed
  namespace: echoserver
  labels:
    app: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
      annotations:
        kubeVipBalanceIP: "true"
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echoserver
        ports:
        - containerPort: 8080
          name: echosrv-http
          protocol: TCP
        resources:
          requests:
            memory: 128Mi
            cpu: 0.1
          limits:
            memory: 128Mi
            cpu: 0.1
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
  annotations:
    kubeVipBalancePriority: "vkube-4, vkube-6, vkube-5"
spec:
  ports:
  - name: echosrv-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "10.115.199.125"